from setuptools import setup, find_packages

setup(
    name="proyecto-registro-imagenes",
    version="0.1.0",
    description="Proyecto: Registro de Imágenes y Medición del Mundo Real",
    author="David A. Londoño",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "opencv-python>=4.8.0",
        "opencv-contrib-python>=4.8.0",
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "matplotlib>=3.8.0",
        "seaborn>=0.13.0",
        "scikit-image>=0.22.0",
        "Pillow>=10.1.0",
        "imutils>=0.5.4",
        "jupyter>=1.0.0",
        "ipykernel>=6.27.0",
        "ipywidgets>=8.1.0",
        "notebook>=7.0.0",
        "pandas>=2.1.0",
        "tqdm>=4.66.0",
        "colorama>=0.4.6",
        "pytest>=7.4.0",
        "pytest-cov>=4.1.0",
        "black>=23.12.0",
        "flake8>=6.1.0",
        "autopep8>=2.0.0",
        "openpyxl>=3.1.0",
        "reportlab>=4.0.0",
    ],
)
